QuintenQVD0/Q_eggs

Readme.md, egg-s-a--m-p.json
hello, I currently have no time to test if this works on arm64 so can someone test this out for me?
IF it works:
closes #12
=> Add SA-MP egg

Readme.md, egg-t-mod-loader-a-r-m.json
=> add Tmodloader

Readme.md, egg-counter--strike--global-offensive.json, steamgames.sh
=> Add Steamcmd + counter strike

Readme.md, egg-valheim.json
add valheim
Needs the SteamCMD for the host!
=> add valheim

egg-beamMP-servers-ARM64.json
1. [ ] Does your submission pass tests (server is connectable)?
3. [ ] Have you added the server to the main README.md?
4. [ ] Have you added a unique README.md for the server you are adding?
1. [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [ ] Have you tested your Egg changes?
=> rename beanmp variable name

Readme.md, egg-paper--hibernation.json
=> add paper-hibernation

Readme.md, egg-7-days-to-die-a-r-m64.json
2. [] Does your server use a custom docker image?
=> add 7 days to die

Readme.md, egg-rage--m-p.json
=> add rage-mp

Readme.md, egg-assetto-server.json
2. [x] Does your server use a custom docker image?
=> add AssettoServer

egg-multi-theft-auto.json
=> add player limit to MTA

egg-s-a--m-p.json
- change install image
- add rcon
- add version
- update to new download URL
=> Merge SAMP upstream and fix download URL

Readme.md, egg-the-front-a-r-m64.json
- This must be retested on Oracle but add The Front server
2. [x] Does your server use a custom docker image?
=> add The Front

Readme.md, egg-factorio-a-r-m64.json
=> add Factorio

Readme.md, egg-satisfactory-a-r-m64.json
closes #71 
2. [] Does your server use a custom docker image?
=> add Satisfactory

egg-satisfactory-a-r-m64.json
- hotfix for Satisfactory because the HOME variable gets losed in the emulation
=> Satisfactory: fix save games

Readme.md, egg-garrys-mod-a-r-m64.json
2. Does your server use a custom docker image?
If i didn't do any of this correctly, please let me know. I'm very new to Github pull requests etc.
=> Add Garry's Mod ARM64

egg-assetto-server.json
=> AssettoServer dotnet 7 and 8

Readme.md, egg-beamMP-servers-ARM64.json
=> Update beamMP for native ARM64

Readme.md, game_eggs/steamcmd/egg-palworld-a-r-m64.json
closes #82 
1. [ ] Does your submission pass tests (server is connectable)?
=> add Palworld

Readme.md, game_eggs/gta/egg-five-m-a-r-m64.json, game_eggs/steamcmd/egg-palworld-a-r-m64.json, game_eggs/steamcmd/egg-s-c-p--s-l--exiled--a-r-m64.json, game_eggs/steamcmd/egg-satisfactory-a-r-m64.json, game_eggs/steamcmd/egg-the-front-a-r-m64.json
This is a work in progress to allow to share a FEX RootFS between servers with a mount
=> Update for custom RootFS PATH

game_eggs/steamcmd/egg-enshrouded-a-r-m64.json
=> add FEX_ROOTFS_PATH to Enshrouded

game_eggs/steamcmd/egg-palworld-a-r-m64.json
=> fix the Palworld Startup

game_eggs/gta/egg-s-a--m-p.json
This seems to be "more offical"
1. [ ] Does your submission pass tests (server is connectable)?
3. [ ] Have you added the server to the main README.md?
4. [ ] Have you added a unique README.md for the server you are adding?
1. [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
2. [ ] Have you tested your Egg changes?
=> Samp: other download link

Readme.md, game_eggs/path_of_titans/egg-path-of-titans-a-r-m64.json
1. [x ] Does your submission pass tests (server is connectable)?
=> Path of Titans egg

game_eggs/steamcmd/egg-satisfactory-a-r-m64.json
* x ] Have you followed the guidelines in our Contributing document?
=> Update satisfactory for 1.0 release

game_eggs/steamcmd/egg-s-c-p--s-l--exiled--a-r-m64.json, game_eggs/steamcmd/egg-satisfactory-a-r-m64.json
Bump 2 eggs to use a newer version of FEX to improve stability and crashing
Closes #139 #46
=> Fex latest

Readme.md, game_eggs/minecraft/egg-vanilla-bedrock-a-r-m64--b-o-x64.json, game_eggs/minecraft/egg-vanilla-bedrock-a-r-m64--f-e-x.json
=> Update bedrock for new download URL and add a FEX version

Readme.md, game_eggs/steamcmd/egg-smalland--survive-the-wilds-a-r-m64.json
closes #143 
2. [] Does your server use a custom docker image?
=> add: Smalland: Survive the Wild
